port: 3000
ip: 0.0.0.0
JWT:
  useJWT: false
  secret: "your_secret_key"
databaseStyle: "nodedb" # Possible values: nodedb, json, yml, sec_nodedb
encryptionKey: "your_encryption_key" # Only required if databaseStyle is sec_nodedb
rateLimit:
  windowMs: 15 * 60 * 1000 # Limit Reset (15 minutes)
  max: 100 # Limit each IP to 100 requests per windowMs
